clone:
    depth: 1

definitions:
    caches:
        node-modules: $BITBUCKET_CLONE_DIR/client/node_modules

image: bsell/yarn-npm-dotnet-cypress-bower:8-2.0.4

build-and-test: &build-and-test
    - step:
        name: Build & Test
        artifacts:
            - dist/**
        caches:
            - node-modules
        script:
            - npm install
            - "[[ $BITBUCKET_BRANCH == develop ]] && BUILDSCRIPT=local"
            - "[[ $BITBUCKET_BRANCH == uat ]] && BUILDSCRIPT=stage"
            - "[[ $BITBUCKET_BRANCH == master ]] && BUILDSCRIPT=prod"
            - npm run $BUILDSCRIPT &> /tmp/client_build.out &
            - export CLIENT_BUILD=$!
            - npm run testSingleRun &> /tmp/client_test.out &
            - export CLIENT_TEST=$!
            - wait $CLIENT_BUILD || (cat /tmp/client_build.out && exit 1)
            - cat /tmp/client_build.out
            - wait $CLIENT_TEST || (cat /tmp/client_test.out && exit 1)
            - cat /tmp/client_test.out

deploy: &deploy
    - <<: *build-and-test
    - step:
        name: Deploy
        script:
            - cd dist
            - git init
            - git config user.email walle@jrbeutler.com
            - git add --all
            - git commit --message "Code Shipped by Bitbucket CI" || echo "Up to date"
            - "[[ $BITBUCKET_BRANCH == develop ]] && DEPLOYENV=dev && PASSWORD=$AZURE_PASSWORD_DEV"
            - "[[ $BITBUCKET_BRANCH == uat ]] && DEPLOYENV=uat && PASSWORD=$AZURE_PASSWORD_UAT"
            - "[[ $BITBUCKET_BRANCH == master ]] && DEPLOYENV=prod && PASSWORD=$AZURE_PASSWORD_PROD"
            - USERNAME=$DOLLAR_SIGN$PROJECT_KEY-web-$DEPLOYENV
            - echo Deploying to $DEPLOYENV
            - git push --force --set-upstream https://$USERNAME:$PASSWORD@$PROJECT_KEY-web-$DEPLOYENV.scm.azurewebsites.net:443/$PROJECT_KEY-web-$DEPLOYENV.git master



pipelines:
    default: *build-and-test
    branches:
        develop: *deploy
        uat: *deploy
        master: *deploy