name: tinyhands-client-build-test
run-name: ${{ github.actor }} build and test client
on: [push]
env:
   SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}
   SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}
   SL_USER: ${{secrets.SL_STAGING_SSH_USER}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm install 
      - run: npm run testSingleRun
      - name: Write SSH key
        run: |
         echo "$SL_PRIVATE_KEY" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
      - name: Install SSH key for staging
        if: github.ref == 'refs/heads/feature/github-action'
        uses: shimataro/ssh-key-action@v2
        with:
           key: ~/.ssh/id_rsa
           known_hosts: $SL_HOST
      - name: Configure SSH known hosts
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan $SL_HOST >> ~/.ssh/known_hosts
      - name: build and copy to staging
        if: github.ref == 'refs/heads/feature/github-action'
        run: |
           npm run stage
           rsync -r -e "ssh -i ~/.ssh/id_rsa" ./dist/ $SL_USER@$SL_HOST:/home/$SL_USER/tinyhands/


