name: tinyhands-client-build-test
run-name: ${{ github.actor }} build and test client
on: [push]
env:
   SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}
   SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}
   SL_USER: ${{secrets.SL_STAGING_SSH_USER}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm install 
      - run: npm run testSingleRun
      - if: github.ref == 'refs/heads/feature/github-action'
        run: |
           echo "$SL_PRIVATE_KEY" > ../private.key
           sudo chmod 600 ../private.key
           mkdir -p ~/.ssh/
           echo "$SL_HOST" > ~/.ssh/known_hosts
           npm run stage
           scp -i ../private.key -r ./dist $SL_USER@$SL_HOST/home/thi/tinyhands/dist
        env:
           SL_PRIVATE_KEY: ${{secrets.SL_STAGING_SSH_KEY}}
           SL_HOST: ${{secrets.SL_STAGING_SSH_HOST}}
           SL_USER: ${{secrets.SL_STAGING_SSH_USER}}


